"""empty message

Revision ID: ef3a825c40d8
Revises: ffdc0a98111c
Create Date: 2021-12-14 14:50:07.726574

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ef3a825c40d8'
down_revision = 'ffdc0a98111c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('discordHandle', sa.String(), nullable=False))
    op.add_column('users', sa.Column('fName', sa.String(), nullable=False))
    op.add_column('users', sa.Column('profilePhoto', sa.String(), nullable=True))
    op.add_column('users', sa.Column('createdAt', sa.DateTime(), nullable=False))
    op.add_column('users', sa.Column('updatedAt', sa.DateTime(), nullable=False))
    op.drop_constraint('users_username_key', 'users', type_='unique')
    op.create_unique_constraint(None, 'users', ['discordHandle'])
    op.create_unique_constraint(None, 'users', ['fName'])
    op.drop_column('users', 'username')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('username', sa.VARCHAR(length=40), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_constraint(None, 'users', type_='unique')
    op.create_unique_constraint('users_username_key', 'users', ['username'])
    op.drop_column('users', 'updatedAt')
    op.drop_column('users', 'createdAt')
    op.drop_column('users', 'profilePhoto')
    op.drop_column('users', 'fName')
    op.drop_column('users', 'discordHandle')
    # ### end Alembic commands ###
